DROP TABLE IF EXISTS USER;

CREATE TABLE USUARIOS(
    USER_ID VARCHAR(36) PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(300) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_DATE()
);